name: Continuous Deployment Project

on:
  push:
    branches:
      - master
      - feat/mglu-9/cicd-github-actions

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Run Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jfrossetto/orderbatch:001
